[package]
name = "smartcalc"
version = "0.1.0"
authors = ["Erhan BARIS <erhanbaris@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsmartcalc = { path = "libsmartcalc" }

[features]
default = []
debug-rules = ["libsmartcalc/debug-rules"]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[workspace]
members = [ "libsmartcalc" ]