[package]
name = "smartcalc"
version = "0.1.0"
authors = ["Erhan BARIS <erhanbaris@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "*"
serde = "1.0"
serde_json = "1.0"
chrono = "0.4"
chrono-tz = "0.4"